train_input:
    train_path: "../data/train.hdf5"
    eval_path: "../data/val.hdf5"
    # 5000, 9950, 10130
    enc_start: 2500
    enc_end: 4975
    dim_half: 5065
    shuffle: True
    batch_size: 32

model:
    embed_dim: 128 # positional_encoding_d
    dense_dim: 64
    num_heads: 8

    share_encoder_decoder_embedding: False
    mixed_precision: True
    boundary_casting: False
    tf_summary: False

optimizer:
    beta1: 0.9
    beta2: 0.999
    epsilon: 1.0e-08
    learning_rate: 0.001

### Cerebras parameters.
runconfig:
    max_steps: 100000
    eval_steps: 187
    save_summary_steps: 100
    save_checkpoints_steps: 10000
    keep_checkpoint_max: 5
    tf_random_seed: 1202
    enable_distributed: False
    multireplica: True

### CS-specific configurations.
csconfig:
    use_cbfloat16: False
