# GPT-2 large model (774M parameters)

train_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./gpt2_hdf5_512k_msl1024/"
    vocab_size: 50257
    max_sequence_length: 1024
    batch_size: 32
    shuffle: True
    shuffle_seed: 1337
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True # Important to avoid seeding at each epoch

eval_input:
    data_processor: "GptHDF5DataProcessor"
    data_dir: "./gpt2_hdf5_val_msl1024/"
    vocab_size: 50257
    max_sequence_length: 1024
    batch_size: 32
    shuffle: False
    num_workers: 8

model:
    # Embedding
    vocab_size: 50257
    hidden_size: 1280
    use_position_embedding: True
    position_embedding_type: "learned"
    share_embedding_weights: True
    max_position_embeddings: 1024

    # Encoder
    num_hidden_layers: 36
    dropout_rate: 0.1
    layer_norm_epsilon: 1.0e-5

    # Encoder - Attention
    num_heads: 20
    attention_type: "scaled_dot_product"
    attention_dropout_rate: 0.1
    use_projection_bias_in_attention: True
    use_ffn_bias_in_attention: True

    # Encoder - ffn
    filter_size: 5120
    nonlinearity: "gelu"
    use_ffn_bias: True

    # Task-specific
    use_bias_in_output: False
    loss_weight: 0.0009765625 # = 1/max_sequence_length

    # Cerebras parameters
    mixed_precision: True

optimizer:
    optimizer_type: "AdamW"
    correct_bias: True
    disable_lr_steps_reset: False
    weight_decay_rate: 0.01
    learning_rate: 0.0002
    loss_scaling_factor: "dynamic"

runconfig:
    max_steps: 200000
    log_steps: 100
    checkpoint_steps: 10000
    seed: 1
    model_dir: "./model_dir"
    show_debug_metrics: False
    save_losses: True
    eval_steps: 233
