# Copyright 2020 Cerebras Systems.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Params for UNet model on Severstal Steel Defect Detection.

train_input:
    shuffle: True
    shuffle_buffer_size: 1000
    dataset: "SeverstalTFRecordsDataset"
    description: "UNet base model params on severstal TFRecords dataset"
    dataset_path: "/path/to/severstal/tfrecords/dataset"
    train_batch_size: 256
    eval_batch_size: 32
    num_parallel_reads: 16
    augment_data: True
    image_shape: [256, 256, 1]
    num_classes: 2

model:
    skip_connect: True
    enable_bias: True
    data_format: "channels_first" # or "channels_last" for running on CPU
    downscale_method: "max_pool"
    convs_per_block: ["3x3_conv", "3x3_conv"]
    encoder_filters: [32, 64, 128, 256]
    decoder_filters: [128, 64, 32]
    initializer: "glorot_uniform"
    bias_initializer: "zeros"
    # Evalution metrics, possible values:
    # mIOU: Mean-Intersection over Union
    # DSC: Dice Similarity Coefficient
    # MPCA: Mean Per-Class Accuracy
    # Acc: Pixel Accuracy
    eval_metrics: ["mIOU", "DSC", "MPCA"]
    boundary_casting: False
    mixed_precision: True
    tf_summary: False
    log_image_summaries: False

optimizer:
    optimizer_type: "adam"
    learning_rate: 5.0e-4
    log_summaries: True
    log_grads: False
    log_hists: False
    loss_scaling_factor: "dynamic"

runconfig:
    max_steps: 12000
    save_summary_steps: 100
    save_checkpoints_steps: 500
    keep_checkpoint_max: 2
    log_step_count_steps: 100
    model_dir: "model_dir_unet_base_severstal_tfrecords"
    cs_ip:
    mode: "train"

### CS-specific configurations 
csconfig:
    use_cbfloat16: False
