#BERT-NER-Base

train_input:
    data_processor: BertTokenClassifierDataProcessor
    data_dir: "./bc5cdr-chem-csv/train"
    vocab_file: "./vocab/Pubmed_fulltext_vocab.txt"
    label_vocab_file: "./bc5cdr-chem-csv/train/label2id.json"
    max_sequence_length: 128
    batch_size: 8
    shuffle: True
    num_workers: 1

eval_input:
    data_processor: BertTokenClassifierDataProcessor
    data_dir: "./bc5cdr-chem-csv/dev"
    vocab_file: "./vocab/Pubmed_fulltext_vocab.txt"
    label_vocab_file: "./bc5cdr-chem-csv/train/label2id.json"
    max_sequence_length: 128
    batch_size: 8
    shuffle: False
    num_workers: 1

model:
    vocab_size: 30522
    hidden_size: 768
    num_hidden_layers: 12
    num_heads: 12
    filter_size: 3072
    encoder_nonlinearity: "gelu"
    max_position_embeddings: 512
    encoder_output_dropout_rate: 0.1
    num_classes: 7
    mixed_precision: True
    compute_eval_metrics: True

optimizer:
    optimizer_type: "Adam" # {"SGD", "AdamW", "Adam"}
    epsilon: 1e-6
    max_gradient_norm: 1.0
    disable_lr_steps_reset: True
    learning_rate:
        - scheduler: "Linear"
          steps: 1508  # 10% of max_steps
          initial_learning_rate: 0.0
          end_learning_rate: 0.00001
        - scheduler: "Linear"
          steps: 15080
          initial_learning_rate: 0.00001
          end_learning_rate: 0
    loss_scaling_factor: "dynamic"
    log_summaries: True

runconfig:
    max_steps: 15080 # 20 epochs
    log_steps: 100
    checkpoint_steps: 1000
    seed: 1
    show_debug_metrics: False
    save_losses: True
    model_dir: "./model_dir"
    save_initial_checkpoint: True
    eval_steps: 759
