# BERT-Large, MSL:512

train_input:
    data_processor: "BertCSVDynamicMaskDataProcessor"
    data_dir: "./owt_pretraining_csv/train_512k_uncased_msl512/"
    vocab_file: "../../vocab/google_research_uncased_L-12_H-768_A-12.txt"
    max_sequence_length: 512
    max_predictions_per_seq: 80
    batch_size: 256 # for GPU(16GB) set batch_size: 16
                    # 16 * 16 = 256 with grad_accum_steps: 16
    whole_word_masking: False
    do_lower: True
    masked_lm_prob: 0.15
    shuffle: True
    shuffle_seed: 1
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True

eval_input:
    data_processor: "BertCSVDynamicMaskDataProcessor"
    data_dir: "./owt_pretraining_csv/val_uncased_msl512/"
    vocab_file: "../../vocab/google_research_uncased_L-12_H-768_A-12.txt"
    max_sequence_length: 512
    max_predictions_per_seq: 80
    batch_size: 256 # for GPU(16GB) set batch_size: 16
    whole_word_masking: False
    do_lower: True
    masked_lm_prob: 0.15
    shuffle: False
    shuffle_seed: 1 # also for deterministic masking
    num_workers: 1
    prefetch_factor: 10
    persistent_workers: True

model:
    vocab_size: 30522
    hidden_size: 1024
    num_hidden_layers: 24
    num_heads: 16
    filter_size: 4096
    encoder_nonlinearity: "gelu" # {"gelu", "relu", "silu", "gelu_new"}
    dropout_rate: 0.1
    attention_dropout_rate: 0.1
    max_position_embeddings: 512
    mlm_loss_weight: 0.019
    layer_norm_epsilon: 1.0e-5
    mixed_precision: True

optimizer:
    optimizer_type: "AdamW"
    weight_decay_rate: 0.01
    disable_lr_steps_reset: True
    learning_rate:
       - scheduler: "Linear"
         initial_learning_rate: 0.0
         end_learning_rate: 0.0001
         steps: 10000
       - scheduler: "Linear"
         initial_learning_rate: 0.0001
         end_learning_rate: 0.0
         steps: 1000000  
    loss_scaling_factor: "dynamic"
    max_gradient_norm: 1.0
#    grad_accum_steps: 64 # helps fit in GPU memory

runconfig:
    max_steps: 900000
    log_steps: 100
    checkpoint_steps: 1000
    seed: 1
    show_debug_metrics: False
    save_losses: True
    save_initial_checkpoint: True
    eval_steps: 74
